import type { Model } from "mongoose";
import { RESOURCE_KEYS } from "@/config/resources";
import {
  Student,
  Parent,
  Teacher,
  Staff,
  SchoolClass,
  Section,
  Subject,
  AcademicSession,
  Attendance,
  TeacherAttendance,
  Timetable,
  Homework,
  Exam,
  ExamSchedule,
  Mark,
  Result,
  FeeStructure,
  StudentFee,
  FeePayment,
  Expense,
  SalaryStructure,
  Payroll,
  LeaveType,
  LeaveRequest,
  Book,
  BookIssue,
  Vehicle,
  TransportRoute,
  TransportAssignment,
  InventoryItem,
  InventoryTransaction,
  Notice,
  Notification,
  Document,
} from "@/models/workspace";

export const RESOURCE_MODELS: Record<string, Model<unknown>> = {
  students: Student as Model<unknown>,
  parents: Parent as Model<unknown>,
  teachers: Teacher as Model<unknown>,
  staff: Staff as Model<unknown>,
  classes: SchoolClass as Model<unknown>,
  sections: Section as Model<unknown>,
  subjects: Subject as Model<unknown>,
  academicSessions: AcademicSession as Model<unknown>,
  attendance: Attendance as Model<unknown>,
  teacherAttendance: TeacherAttendance as Model<unknown>,
  timetable: Timetable as Model<unknown>,
  homework: Homework as Model<unknown>,
  exams: Exam as Model<unknown>,
  examSchedules: ExamSchedule as Model<unknown>,
  marks: Mark as Model<unknown>,
  results: Result as Model<unknown>,
  fees: StudentFee as Model<unknown>,
  feeStructures: FeeStructure as Model<unknown>,
  payments: FeePayment as Model<unknown>,
  expenses: Expense as Model<unknown>,
  salaryStructures: SalaryStructure as Model<unknown>,
  payroll: Payroll as Model<unknown>,
  leaveTypes: LeaveType as Model<unknown>,
  leave: LeaveRequest as Model<unknown>,
  library: Book as Model<unknown>,
  bookIssues: BookIssue as Model<unknown>,
  transport: Vehicle as Model<unknown>,
  routes: TransportRoute as Model<unknown>,
  transportAssignments: TransportAssignment as Model<unknown>,
  inventory: InventoryItem as Model<unknown>,
  inventoryTransactions: InventoryTransaction as Model<unknown>,
  notices: Notice as Model<unknown>,
  notifications: Notification as Model<unknown>,
  documents: Document as Model<unknown>,
};

export function getResourceModel(key: string) {
  if (!RESOURCE_KEYS.includes(key) || !RESOURCE_MODELS[key]) {
    return null;
  }
  return RESOURCE_MODELS[key];
}
