export type FieldType = "text" | "number" | "textarea" | "select" | "date";

export type ResourceConfig = {
  key: string;
  collection: string;
  label: string;
  permission: string;
  searchFields: string[];
  columns: Array<{ key: string; label: string }>;
  fields: Array<{
    name: string;
    label: string;
    type?: FieldType;
    required?: boolean;
    options?: string[];
  }>;
};

export const RESOURCES: Record<string, ResourceConfig> = {
  students: {
    key: "students",
    collection: "students",
    label: "Students",
    permission: "students",
    searchFields: ["name", "admissionNumber", "email"],
    columns: [
      { key: "photo", label: "Photo" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentCode", label: "Student ID" },
      { key: "name", label: "Name" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "dateOfBirth", label: "Date of Birth" },
      { key: "gender", label: "Gender" },
      { key: "parentName", label: "Parent Name" },
      { key: "parentMobile", label: "Parent Mobile" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "admissionNumber", label: "Admission Number", required: true },
      { name: "name", label: "Name", required: true },
      { name: "gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { name: "dateOfBirth", label: "Date of Birth", type: "date" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] },
    ],
  },
  parents: {
    key: "parents",
    collection: "parents",
    label: "Parents / Guardians",
    permission: "parents",
    searchFields: ["name", "email", "phone"],
    columns: [
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "phone", label: "Phone" },
      { key: "relation", label: "Relation" },
      { key: "linkedStudents", label: "Linked Students" },
      { key: "username", label: "Login" },
      { key: "loginStatus", label: "Account" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
      { name: "relation", label: "Relation", type: "select", options: ["Father", "Mother", "Guardian"] },
      { name: "address", label: "Address", type: "textarea" },
      { name: "studentIds", label: "Linked Students" },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] },
    ],
  },
  teachers: {
    key: "teachers",
    collection: "teachers",
    label: "Teachers",
    permission: "teachers",
    searchFields: ["name", "employeeId", "email"],
    columns: [
      { key: "photo", label: "Photo" },
      { key: "employeeId", label: "Employee ID" },
      { key: "name", label: "Name" },
      { key: "email", label: "Email" },
      { key: "department", label: "Department" },
      { key: "username", label: "Login" },
      { key: "loginStatus", label: "Account" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "employeeId", label: "Employee ID", required: true },
      { name: "name", label: "Name", required: true },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
      { name: "department", label: "Department" },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE"] },
    ],
  },
  staff: {
    key: "staff",
    collection: "staff",
    label: "Staff",
    permission: "staff",
    searchFields: ["name", "employeeId", "email"],
    columns: [
      { key: "employeeId", label: "Employee ID" },
      { key: "name", label: "Name" },
      { key: "staffType", label: "Staff Type" },
      { key: "department", label: "Department" },
      { key: "designation", label: "Designation" },
      { key: "email", label: "Email" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "employeeId", label: "Employee ID", required: true },
      { name: "name", label: "Name", required: true },
      { name: "staffType", label: "Staff Type", type: "select", options: ["Teacher", "Administrative", "Support", "Other"], required: true },
      { name: "email", label: "Email" },
      { name: "phone", label: "Phone" },
      { name: "department", label: "Department" },
      { name: "designation", label: "Designation" },
      { name: "qualification", label: "Qualification" },
      { name: "experience", label: "Experience" },
      { name: "joiningDate", label: "Joining Date", type: "date" },
      { name: "enablePortalLogin", label: "Enable Portal Login (Teachers)", type: "select", options: ["true", "false"] },
      { name: "status", label: "Status", type: "select", options: ["ACTIVE", "INACTIVE", "ON_LEAVE"] },
    ],
  },
  classes: {
    key: "classes",
    collection: "classes",
    label: "Classes",
    permission: "classes",
    searchFields: ["name"],
    columns: [
      { key: "name", label: "Class" },
      { key: "numericName", label: "Order" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Class Name", required: true },
      { name: "numericName", label: "Class Order", type: "number" },
    ],
  },
  sections: {
    key: "sections",
    collection: "sections",
    label: "Sections",
    permission: "sections",
    searchFields: ["name"],
    columns: [
      { key: "className", label: "Class" },
      { key: "classOrder", label: "Class Order" },
      { key: "name", label: "Section Name" },
      { key: "classTeacherName", label: "Class Teacher" },
      { key: "capacity", label: "Capacity" },
      { key: "studentCount", label: "Students" },
      { key: "availableSeats", label: "Available Seats" },
    ],
    fields: [
      { name: "classId", label: "Class", required: true },
      { name: "classOrder", label: "Class Order", type: "number", required: true },
      { name: "name", label: "Section Name", required: true },
      { name: "classTeacherId", label: "Class Teacher" },
      { name: "capacity", label: "Capacity", type: "number", required: true },
    ],
  },
  subjects: {
    key: "subjects",
    collection: "subjects",
    label: "Subjects",
    permission: "subjects",
    searchFields: ["name", "code"],
    columns: [
      { key: "className", label: "Class" },
      { key: "classOrder", label: "Class Order" },
      { key: "name", label: "Subject Name" },
      { key: "code", label: "Subject Code" },
    ],
    fields: [
      { name: "classId", label: "Class", required: true },
      { name: "classOrder", label: "Class Order", type: "number", required: true },
      { name: "name", label: "Subject Name", required: true },
      { name: "code", label: "Subject Code", required: true },
    ],
  },
  academicSessions: {
    key: "academicSessions",
    collection: "academicSessions",
    label: "Academic Sessions",
    permission: "settings",
    searchFields: ["name"],
    columns: [
      { key: "name", label: "Session" },
      { key: "startDate", label: "Start" },
      { key: "endDate", label: "End" },
    ],
    fields: [
      { name: "name", label: "Session Name", required: true },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
    ],
  },
  attendance: {
    key: "attendance",
    collection: "attendance",
    label: "Attendance",
    permission: "attendance",
    searchFields: ["date", "status"],
    columns: [
      { key: "date", label: "Date" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "status", label: "Status" },
      { key: "remarks", label: "Remarks" },
    ],
    fields: [
      { name: "studentId", label: "Student ID", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: ["PRESENT", "ABSENT", "LATE", "LEAVE"], required: true },
      { name: "remarks", label: "Remarks" },
    ],
  },
  teacherAttendance: {
    key: "teacherAttendance",
    collection: "teacherAttendance",
    label: "Teacher Attendance",
    permission: "teacherAttendance",
    searchFields: ["date", "status"],
    columns: [
      { key: "date", label: "Date" },
      { key: "teacherName", label: "Teacher" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "teacherId", label: "Teacher ID", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "status", label: "Status", type: "select", options: ["PRESENT", "ABSENT", "LATE", "LEAVE"], required: true },
    ],
  },
  timetable: {
    key: "timetable",
    collection: "timetables",
    label: "Timetable",
    permission: "timetable",
    searchFields: ["day", "period"],
    columns: [
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "day", label: "Day" },
      { key: "period", label: "Period" },
      { key: "subjectName", label: "Subject" },
      { key: "teacherName", label: "Teacher" },
    ],
    fields: [
      { name: "classId", label: "Class ID", required: true },
      { name: "sectionId", label: "Section ID" },
      { name: "day", label: "Day", required: true },
      { name: "period", label: "Period", required: true },
      { name: "subjectId", label: "Subject ID" },
      { name: "teacherId", label: "Teacher ID" },
    ],
  },
  homework: {
    key: "homework",
    collection: "homework",
    label: "Homework",
    permission: "homework",
    searchFields: ["title", "description"],
    columns: [
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "subjectName", label: "Subject" },
      { key: "title", label: "Title" },
      { key: "dueDate", label: "Due Date" },
      { key: "teacherName", label: "Teacher" },
    ],
    fields: [
      { name: "classId", label: "Class Name", required: true },
      { name: "sectionId", label: "Section", required: true },
      { name: "subjectId", label: "Subject" },
      { name: "dueDate", label: "Due Date", type: "date", required: true },
      { name: "title", label: "Title", required: true },
      { name: "description", label: "Description", type: "textarea" },
    ],
  },
  exams: {
    key: "exams",
    collection: "exams",
    label: "Examinations",
    permission: "exams",
    searchFields: ["name", "status"],
    columns: [
      { key: "name", label: "Exam" },
      { key: "className", label: "Class" },
      { key: "startDate", label: "Start" },
      { key: "endDate", label: "End" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "name", label: "Exam Name", required: true },
      { name: "startDate", label: "Start Date", type: "date" },
      { name: "endDate", label: "End Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "SCHEDULED", "ACTIVE", "COMPLETED", "CANCELLED"] },
    ],
  },
  examSchedules: {
    key: "examSchedules",
    collection: "examSchedules",
    label: "Exam Schedules",
    permission: "exams",
    searchFields: ["date"],
    columns: [
      { key: "examName", label: "Exam" },
      { key: "className", label: "Class" },
      { key: "subjectName", label: "Subject" },
      { key: "date", label: "Date" },
      { key: "startTime", label: "Start" },
      { key: "maxMarks", label: "Max Marks" },
    ],
    fields: [
      { name: "examId", label: "Exam ID", required: true },
      { name: "date", label: "Date", type: "date" },
      { name: "startTime", label: "Start Time" },
      { name: "endTime", label: "End Time" },
      { name: "maxMarks", label: "Max Marks", type: "number" },
    ],
  },
  marks: {
    key: "marks",
    collection: "marks",
    label: "Marks",
    permission: "marks",
    searchFields: ["grade"],
    columns: [
      { key: "examName", label: "Exam" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "subjectName", label: "Subject" },
      { key: "marksObtained", label: "Marks" },
      { key: "maxMarks", label: "Max" },
      { key: "grade", label: "Grade" },
    ],
    fields: [
      { name: "examId", label: "Exam", required: true },
      { name: "studentId", label: "Student", required: true },
      { name: "subjectId", label: "Subject" },
      { name: "marksObtained", label: "Gained Marks", type: "number", required: true },
      { name: "maxMarks", label: "Total Marks", type: "number" },
      { name: "grade", label: "Rating" },
    ],
  },
  results: {
    key: "results",
    collection: "results",
    label: "Results",
    permission: "results",
    searchFields: ["grade", "status"],
    columns: [
      { key: "examName", label: "Exam" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "totalMarks", label: "Total" },
      { key: "percentage", label: "Percentage" },
      { key: "grade", label: "Grade" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "examId", label: "Exam", required: true },
      { name: "studentId", label: "Student", required: true },
      { name: "totalMarks", label: "Total Marks", type: "number" },
      { name: "percentage", label: "Percentage", type: "number" },
      { name: "grade", label: "Grade" },
      { name: "status", label: "Status", type: "select", options: ["PASS", "FAIL"] },
    ],
  },
  fees: {
    key: "fees",
    collection: "studentFees",
    label: "Student Fees",
    permission: "fees",
    searchFields: ["status"],
    columns: [
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "feeHead", label: "Fee Head" },
      { key: "description", label: "Description" },
      { key: "amount", label: "Amount" },
      { key: "paidAmount", label: "Paid" },
      { key: "dueAmount", label: "Balance" },
      { key: "statusLabel", label: "Status" },
      { key: "dueDate", label: "Due Date" },
    ],
    fields: [
      { name: "studentName", label: "Student" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "description", label: "Description", type: "textarea" },
      { name: "dueDate", label: "Due Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["PENDING", "PARTIAL", "PAID"] },
    ],
  },
  feeStructures: {
    key: "feeStructures",
    collection: "feeStructures",
    label: "Fee Structures",
    permission: "fees",
    searchFields: ["name"],
    columns: [
      { key: "name", label: "Name" },
      { key: "className", label: "Class" },
      { key: "amount", label: "Amount" },
      { key: "frequency", label: "Frequency" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "frequency", label: "Frequency", type: "select", options: ["MONTHLY", "QUARTERLY", "ANNUAL"] },
    ],
  },
  payments: {
    key: "payments",
    collection: "feePayments",
    label: "Fee Payments",
    permission: "payments",
    searchFields: ["receiptNumber", "method", "transactionRef", "verificationStatus"],
    columns: [
      { key: "receiptNumber", label: "Receipt" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "feeHead", label: "Fee Head" },
      { key: "amount", label: "Amount" },
      { key: "method", label: "Method" },
      { key: "date", label: "Date" },
      { key: "verificationStatusLabel", label: "Verification" },
      { key: "remarks", label: "Remarks" },
    ],
    fields: [
      { name: "studentId", label: "Student ID", required: true },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "method", label: "Method", type: "select", options: ["CASH", "UPI", "CARD", "BANK"] },
      { name: "receiptNumber", label: "Receipt Number", required: true },
      { name: "date", label: "Date", type: "date", required: true },
    ],
  },
  expenses: {
    key: "expenses",
    collection: "expenses",
    label: "Expenses",
    permission: "expenses",
    searchFields: ["title", "category"],
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
      { key: "amount", label: "Amount" },
      { key: "date", label: "Date" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "category", label: "Category" },
      { name: "amount", label: "Amount", type: "number", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
  },
  salaryStructures: {
    key: "salaryStructures",
    collection: "salaryStructures",
    label: "Salary Structures",
    permission: "payroll",
    searchFields: [],
    columns: [
      { key: "teacherName", label: "Employee" },
      { key: "basic", label: "Basic" },
      { key: "allowances", label: "Allowances" },
      { key: "deductions", label: "Deductions" },
    ],
    fields: [
      { name: "basic", label: "Basic", type: "number", required: true },
      { name: "allowances", label: "Allowances", type: "number" },
      { name: "deductions", label: "Deductions", type: "number" },
    ],
  },
  payroll: {
    key: "payroll",
    collection: "payroll",
    label: "Payroll",
    permission: "payroll",
    searchFields: ["staffName", "employeeId", "month"],
    columns: [
      { key: "staffName", label: "Name" },
      { key: "month", label: "Month" },
      { key: "netPay", label: "Net Pay" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "staffName", label: "Staff Name", required: true },
      { name: "employeeId", label: "Employee ID" },
      { name: "month", label: "Month", required: true },
      { name: "basic", label: "Basic", type: "number", required: true },
      { name: "allowances", label: "Allowances", type: "number" },
      { name: "deductions", label: "Deductions", type: "number" },
      { name: "netPay", label: "Net Pay", type: "number", required: true },
      { name: "status", label: "Status", type: "select", options: ["DRAFT", "PAID"] },
    ],
  },
  leaveTypes: {
    key: "leaveTypes",
    collection: "leaveTypes",
    label: "Leave Types",
    permission: "leave",
    searchFields: ["name"],
    columns: [
      { key: "name", label: "Type" },
      { key: "code", label: "Code" },
      { key: "days", label: "Days / Year" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "code", label: "Code" },
      { name: "days", label: "Yearly Entitlement (Days)", type: "number" },
    ],
  },
  leave: {
    key: "leave",
    collection: "leaveRequests",
    label: "Leave Requests",
    permission: "leave",
    searchFields: ["requesterName", "status"],
    columns: [
      { key: "requesterName", label: "Requester" },
      { key: "leaveTypeName", label: "Leave Type" },
      { key: "fromDate", label: "From" },
      { key: "toDate", label: "To" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "requesterName", label: "Teacher / Staff Name", required: true },
      { name: "leaveTypeId", label: "Leave Type" },
      { name: "fromDate", label: "From", type: "date", required: true },
      { name: "toDate", label: "To", type: "date", required: true },
      { name: "reason", label: "Reason", type: "textarea" },
      { name: "status", label: "Status", type: "select", options: ["PENDING", "APPROVED", "REJECTED"] },
    ],
  },
  library: {
    key: "library",
    collection: "books",
    label: "Library Books",
    permission: "library",
    searchFields: ["title", "author", "isbn"],
    columns: [
      { key: "title", label: "Title" },
      { key: "author", label: "Author" },
      { key: "copies", label: "Copies" },
      { key: "available", label: "Available" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "author", label: "Author" },
      { name: "isbn", label: "ISBN" },
      { name: "copies", label: "Copies", type: "number" },
      { name: "available", label: "Available", type: "number" },
    ],
  },
  bookIssues: {
    key: "bookIssues",
    collection: "bookIssues",
    label: "Book Issues",
    permission: "library",
    searchFields: ["status"],
    columns: [
      { key: "bookTitle", label: "Book" },
      { key: "admissionNumber", label: "Admission No" },
      { key: "studentName", label: "Student" },
      { key: "className", label: "Class" },
      { key: "sectionName", label: "Section" },
      { key: "issueDate", label: "Issued" },
      { key: "dueDate", label: "Due" },
      { key: "returnDate", label: "Returned" },
      { key: "status", label: "Status" },
    ],
    fields: [
      { name: "bookId", label: "Book ID", required: true },
      { name: "studentId", label: "Student ID" },
      { name: "issueDate", label: "Issue Date", type: "date", required: true },
      { name: "dueDate", label: "Due Date", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["ISSUED", "RETURNED"] },
    ],
  },
  transport: {
    key: "transport",
    collection: "vehicles",
    label: "Vehicles",
    permission: "transport",
    searchFields: ["number", "driver"],
    columns: [
      { key: "number", label: "Vehicle No" },
      { key: "type", label: "Type" },
      { key: "capacity", label: "Capacity" },
      { key: "driver", label: "Driver" },
    ],
    fields: [
      { name: "number", label: "Vehicle Number", required: true },
      { name: "type", label: "Type" },
      { name: "capacity", label: "Capacity", type: "number" },
      { name: "driver", label: "Driver" },
    ],
  },
  routes: {
    key: "routes",
    collection: "routes",
    label: "Routes",
    permission: "transport",
    searchFields: ["name", "stops"],
    columns: [
      { key: "name", label: "Route" },
      { key: "stops", label: "Stops" },
      { key: "vehicleNumber", label: "Vehicle" },
    ],
    fields: [
      { name: "name", label: "Route Name", required: true },
      { name: "stops", label: "Stops", type: "textarea" },
    ],
  },
  transportAssignments: {
    key: "transportAssignments",
    collection: "transportAssignments",
    label: "Transport Assignments",
    permission: "transport",
    searchFields: ["pickupPoint"],
    columns: [
      { key: "studentName", label: "Student" },
      { key: "routeName", label: "Route" },
      { key: "vehicleNumber", label: "Vehicle" },
      { key: "pickupPoint", label: "Pickup" },
    ],
    fields: [
      { name: "studentId", label: "Student ID", required: true },
      { name: "routeId", label: "Route ID", required: true },
      { name: "pickupPoint", label: "Pickup Point" },
    ],
  },
  inventory: {
    key: "inventory",
    collection: "inventoryItems",
    label: "Inventory",
    permission: "inventory",
    searchFields: ["name", "sku"],
    columns: [
      { key: "name", label: "Item" },
      { key: "sku", label: "SKU" },
      { key: "quantity", label: "Qty" },
      { key: "location", label: "Location" },
    ],
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "sku", label: "SKU", required: true },
      { name: "quantity", label: "Quantity", type: "number" },
      { name: "unit", label: "Unit" },
      { name: "location", label: "Location" },
    ],
  },
  inventoryTransactions: {
    key: "inventoryTransactions",
    collection: "inventoryTransactions",
    label: "Inventory Transactions",
    permission: "inventory",
    searchFields: ["type", "notes"],
    columns: [
      { key: "itemName", label: "Item" },
      { key: "type", label: "Type" },
      { key: "quantity", label: "Qty" },
      { key: "date", label: "Date" },
    ],
    fields: [
      { name: "itemId", label: "Item ID", required: true },
      { name: "type", label: "Type", type: "select", options: ["IN", "OUT"], required: true },
      { name: "quantity", label: "Quantity", type: "number", required: true },
      { name: "date", label: "Date", type: "date", required: true },
      { name: "notes", label: "Notes" },
    ],
  },
  notices: {
    key: "notices",
    collection: "notices",
    label: "Notices",
    permission: "notices",
    searchFields: ["title", "body"],
    columns: [
      { key: "title", label: "Title" },
      { key: "audience", label: "Audience" },
      { key: "date", label: "Date" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "body", label: "Body", type: "textarea" },
      { name: "audience", label: "Audience", type: "select", options: ["ALL", "STAFF", "STUDENTS", "PARENTS"] },
      { name: "date", label: "Date", type: "date" },
    ],
  },
  notifications: {
    key: "notifications",
    collection: "notifications",
    label: "Notifications",
    permission: "notifications",
    searchFields: ["title", "body"],
    columns: [
      { key: "title", label: "Title" },
      { key: "read", label: "Read" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "body", label: "Body", type: "textarea" },
    ],
  },
  documents: {
    key: "documents",
    collection: "documents",
    label: "Documents",
    permission: "documents",
    searchFields: ["title", "category"],
    columns: [
      { key: "title", label: "Title" },
      { key: "category", label: "Category" },
    ],
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "category", label: "Category" },
      { name: "url", label: "URL" },
    ],
  },
};

export const RESOURCE_KEYS = Object.keys(RESOURCES);
