import type { GuideChapter } from "@/lib/guide/types";

export const CORE_CHAPTERS: GuideChapter[] = [
  {
    id: "introduction",
    title: "Introduction",
    keywords: ["what is", "sms erp", "overview", "girjasoft", "purpose"],
    blocks: [
      { type: "p", text: "GirjaSoft SMS ERP is a school management system for one school workspace at a time. Each school’s students, staff, fees, exams and notices stay isolated from other schools." },
      { type: "h", text: "What problems it solves" },
      { type: "ul", items: [
        "One place for admissions, student records, attendance, homework, exams, marks and results.",
        "Finance for fees, receipts, expenses and teacher payroll.",
        "Role-based logins so Admin, Teacher, Accountant, Parent and Student each see only what they are permitted to use.",
        "Printed documents (fee receipts, salary slips, report cards, ID cards) that use the school letterhead.",
      ] },
      { type: "h", text: "Who can use it" },
      { type: "ul", items: [
        "Workspace Admin — full school operations and settings.",
        "Teacher — assigned classes, attendance, homework, exams, marks, own leave and paid salary slips.",
        "Accountant — fees, payments, expenses and reports.",
        "HR Manager — staff, leave types, leave review and payroll.",
        "Librarian / Transport Manager — those service modules when enabled.",
        "Parent — read-only view of linked children.",
        "Student — read-only view of their own academic information.",
      ] },
      { type: "h", text: "Main modules" },
      { type: "p", text: "The Dashboard lists only modules enabled for your school. Typical modules include Admissions, Student Info, Teacher, Attendance, Homework, Exams, Marks, Results, Finance, Leave, Library, Transport, Inventory, Notices and Settings." },
      { type: "h", text: "How the school should use the ERP" },
      { type: "ol", items: [
        "Admin sets organisation details, logo, roles, users and staff.",
        "Create academic sessions, classes, sections and subjects.",
        "Admit or add students and link parents.",
        "Assign teachers to class, section and subject.",
        "Run daily attendance, homework, exams and marks in that order.",
        "Collect fees and publish notices as needed.",
      ] },
      { type: "note", text: "This Guide describes features that exist in GirjaSoft SMS ERP. If a module is turned off for your workspace, it will not appear in the Guide contents." },
    ],
  },
  {
    id: "getting-started",
    title: "Getting Started",
    keywords: ["new user", "first login", "setup", "onboarding"],
    highlightRoles: ["admin"],
    blocks: [
      { type: "p", text: "Use this chapter the first time your school starts using the ERP." },
      { type: "h", text: "For the school administrator" },
      { type: "steps", items: [
        "Sign in with the workspace administrator account (email or username, password, and workspace code if asked).",
        "Open Settings → Organization. Enter school name, address, phone, email and website. Upload the school logo. Set currency and receipt prefix.",
        "Open Settings → Theme to choose a look and confirm letterhead details used on receipts and report cards.",
        "Open Settings → Roles only if you need custom roles. System roles (Workspace Admin, Teacher, Accountant, Parent, Student, and others) already exist.",
        "Open Settings → Users to create office logins, or Settings → Staff to create staff. Teachers are created from Staff when the staff type is Teacher and portal login is enabled.",
        "Open Student Info → Classes, then Sections, then Subjects.",
        "Open Settings → Teacher Assignment and assign each teacher to class, section and subject.",
        "Enable only the modules your school will use (from the workspace module list on the Dashboard / ERP Modules page).",
      ] },
      { type: "h", text: "For a teacher" },
      { type: "steps", items: [
        "Sign in with the teacher username or email.",
        "If asked, select today’s class, section and subject. This context is used for homework, attendance and marks.",
        "Open Teacher → Leave to apply leave, or Teacher → Salary Slips after payroll is marked Paid.",
        "Use Attendance, Homework, Exams and Marks from the sidebar for assigned work only.",
      ] },
      { type: "h", text: "For a parent" },
      { type: "steps", items: [
        "Sign in with the parent login created when the parent record was saved (or after admission conversion).",
        "If more than one child is linked, use Active child in the sidebar to switch.",
        "Open Student Info to see the child profile. Use Attendance, Homework, Exams, Marks, Results, Fees and Notices as read-only views.",
      ] },
      { type: "tip", text: "Open Profile → Help if something is broken. Open Profile → Help → Guide (this book) to learn a module before you use it." },
    ],
  },
  {
    id: "login",
    title: "Login & Account Management",
    keywords: ["login", "password", "forgot", "profile", "sign out", "workspace code"],
    blocks: [
      { type: "h", text: "How users log in" },
      { type: "p", text: "Open the login page. Enter Email / Username and Password. If your school uses a workspace code (for example GIRJA-SCHOOL-001), enter it. Click Login. The system sends you to the Dashboard for school users, or the platform dashboard for GirjaSoft platform administrators." },
      { type: "h", text: "Forgot password" },
      { type: "p", text: "On the login page, click Forgot Password? and follow the email reset steps. After reset, sign in with the new password." },
      { type: "h", text: "Profile menu" },
      { type: "p", text: "Click your initials or photo at the top right." },
      { type: "ul", items: [
        "My Profile — name, photo, and print ID card when available.",
        "Design — personal theme and layout preferences.",
        "Change Password — enter current password and a new password.",
        "Help — support tickets.",
        "Sign Out — ends the session.",
      ] },
      { type: "h", text: "Help and Guide" },
      { type: "p", text: "Help is under the profile menu. On Help & Support, Guide sits to the left of Create Support Request. Guide opens this user manual. Create Support Request still creates a ticket exactly as before." },
      { type: "h", text: "What each role typically sees" },
      { type: "table", headers: ["Role", "After login"], rows: [
        ["Workspace Admin", "Full sidebar: modules that are enabled, Finance, Settings."],
        ["Teacher", "Assigned academic modules, Leave, Salary Slips, no Finance Payroll create."],
        ["Accountant", "Finance (Fees, Payments, Expenses) and Reports."],
        ["Parent", "Linked children only; Create/Edit/Delete hidden on academic records."],
        ["Student", "Own timetable, homework, attendance, exams, results and notices."],
      ] },
      { type: "important", text: "Do not share passwords. Change your password after the first temporary login created by Admin or Staff setup." },
    ],
  },
  {
    id: "dashboard",
    title: "Dashboard",
    keywords: ["dashboard", "erp modules", "widgets", "home"],
    blocks: [
      { type: "h", text: "Purpose" },
      { type: "p", text: "Dashboard (also labelled ERP Modules in the sidebar) is the home page after login. It shows tiles for every module enabled for this school that your role is allowed to open." },
      { type: "h", text: "What you see" },
      { type: "ul", items: [
        "Module cards with name, short description and an icon. Click a card to open that module.",
        "Only enabled modules appear. A module turned off for the workspace is not shown.",
        "Header Dashboard (or the dashboard icon on phone) returns here.",
      ] },
      { type: "h", text: "Other home pages" },
      { type: "p", text: "Some modules have their own dashboards. Admissions shows enquiry and conversion counts. Student Info shows student/parent counts for admin, or a children list for parents. Teacher has a teacher dashboard after class context is chosen." },
      { type: "h", text: "Header shortcuts" },
      { type: "ul", items: [
        "Dashboard — this page.",
        "Reports — workspace summary counts and audit log (if you have reports.view).",
        "Notices — school notices and unread badge (if Comms Center is enabled).",
        "Settings — organisation, users, staff, roles, theme (if permitted).",
        "Profile — account menu.",
      ] },
      { type: "note", text: "Dashboard tiles are not calculated fee or marks widgets. Counts live inside each module dashboard (Admissions, Student Info, Attendance reports, Help ticket counts)." },
    ],
  },
  {
    id: "workspace",
    title: "School Workspace",
    keywords: ["workspace", "school", "isolation", "logo", "code"],
    blocks: [
      { type: "p", text: "A workspace is one school. Data never mixes with another school. The header shows the school logo, school name and workspace code on tablet and desktop. On a phone, only the logo is shown to save space." },
      { type: "h", text: "What Admin maintains" },
      { type: "ul", items: [
        "School name, logo, address, phone, email, website — Settings → Organization.",
        "Currency and receipt prefix — same page, Finance section.",
        "Enabled modules — the Dashboard module list follows what is enabled for the workspace.",
        "Letterhead — used on printed receipts, report cards and salary slips.",
      ] },
      { type: "tip", text: "Upload a clear school logo. It appears on the header and on printed documents." },
    ],
  },
];
