import { moduleDoc } from "@/lib/guide/format";
import type { GuideChapter } from "@/lib/guide/types";

export const ACADEMIC_CHAPTERS: GuideChapter[] = [
  moduleDoc({
    id: "admissions",
    title: "Admission Management",
    moduleId: "admissions",
    keywords: ["admission", "enquiry", "application", "direct admission", "conversion", "documents"],
    purpose: "Capture interest, follow up, collect application details and convert a confirmed admission into a student (and parent) record without typing the child twice.",
    does: "Tracks enquiries, follow-ups, applications, documents, admission fees and confirmation. Direct Admission skips enquiry but still runs the same application checks.",
    who: "Users with admissions.view (typically Workspace Admin or an admission role). Teachers and parents do not run this module unless given that permission.",
    features: [
      "Dashboard: enquiries today, pending follow-ups, applications, confirmed admissions, conversion rate.",
      "Enquiries — New Enquiry from the admissions home.",
      "Follow-ups — schedule and complete callbacks.",
      "Applications — New Application with student, parents, addresses, previous school, documents and fees.",
      "Direct Admission — same application form without a prior enquiry.",
      "Reports — summary and conversion views.",
      "Settings → Admission — ID format, workflow flags and admission fee heads.",
    ],
    open: "Sidebar → Admissions, or Dashboard → Admissions. Path: /modules/admissions.",
    workflow: [
      "Create an Enquiry (student name and contact).",
      "Add Follow-ups until the family is ready.",
      "Create an Application (or use Direct Admission).",
      "Upload required documents and collect admission fee if configured.",
      "Move the application through verification / approval as your workflow settings allow.",
      "Confirm / convert. The system creates or links the Student and Parent records used by Student Info.",
    ],
    create: "On Admissions home click New Enquiry, New Application or Direct Admission. Fill student information, father/mother, addresses, previous school, documents and fee fields, then save.",
    edit: "Open the application from the list or dashboard. Update status, documents or fee collection using the actions on that application (approve, verify, collect, convert, cancel — only those your role is allowed).",
    view: "Admissions home lists recent enquiries, applications, pending payments and pending documents. Open an application by name.",
    search: "Use the lists on Enquiries, Applications and Follow-ups. Dashboard cards jump to pending work.",
    exportPrint: "Admissions → Reports for conversion and summary figures. Print from the browser if you need a paper copy of that report page.",
    roles: [
      ["Open Admissions", "Yes", "Only if permitted", "No"],
      ["Create enquiry / application", "Yes", "Only if permitted", "No"],
      ["Convert to student", "Yes (workflow)", "Only if permitted", "No"],
    ],
    example: "A family walks in. Front office creates an Enquiry, books a Follow-up, then Direct Admission. After confirmation the child appears under Student Info → Students and the parent can receive a login.",
    mistakes: [
      "Creating a student again in Student Info after conversion — that duplicates the child.",
      "Skipping documents or fees when Settings → Admission requires them.",
      "Using a class/section that has no remaining capacity.",
    ],
    practices: [
      "Keep one application per child.",
      "Complete follow-ups so the dashboard conversion rate stays meaningful.",
      "Set admission settings before the admission season starts.",
    ],
    related: "Student Info, Parents, Fees, Settings → Admission.",
  }),
  moduleDoc({
    id: "students",
    title: "Student Information",
    moduleId: "student-info",
    keywords: ["student", "profile", "admission number", "photo", "id card", "promotion"],
    purpose: "Hold the single student record used by attendance, fees, exams, results, library and transport.",
    does: "Stores profile, photo, class/section enrolment, parent links and academic history. Promotion moves the same student to the next class/section for a new session.",
    who: "Admin and staff with students.view. Teachers see assigned students. Parents see only linked children. Students see themselves.",
    features: [
      "Student list: photo, admission no., student ID, name, class, section, date of birth, gender, parent, status.",
      "Create / Edit student, upload photo.",
      "Student profile page and ID card print.",
      "Parents list and linking.",
      "Classes, Sections, Subjects.",
      "Promotion and academic history / archived students.",
    ],
    open: "Sidebar → Student Info, or /modules/student-info. Students list: /modules/student-info/students.",
    workflow: [
      "Confirm Classes, Sections and the academic session exist.",
      "Add Student (or wait for admission conversion).",
      "Enter admission number, name, and other details. Assign class/section only if a seat is free.",
      "Link parent(s) on the parent record or during admission.",
      "Upload photo if you print ID cards.",
      "At year end use Student Info → Promotion: choose session, from class/section, to class/section. The same student record continues (for example Junior KG A in 2026–27 becomes Senior KG A in 2027–28).",
    ],
    create: "Student Info → Students → Create. Required: Admission Number and Name. Optional: gender, date of birth, phone, email, address, status.",
    edit: "Open the student → Edit. Do not change identity fields casually; keep one admission number for the child’s life in the school.",
    view: "Click the student name or card. Parents open the child from My Children on the Student Info home.",
    search: "Search the list by name, admission number or email.",
    exportPrint: "Where Excel export is offered on the list, use it. From the profile or list, print ID cards. Do not print internal database IDs — the screens show admission number and name.",
    roles: [
      ["Create / edit student", "Yes", "No (view assigned)", "No"],
      ["View profile", "Yes", "Assigned class", "Linked child / self"],
      ["Promote students", "Yes", "No", "No"],
    ],
    example: "After admission conversion, open Students, confirm class and section, add a photo, then print the ID card from the profile actions.",
    mistakes: [
      "Creating a second student for the same child in the next session.",
      "Assigning a section that is already at capacity.",
      "Unlinking the parent so the parent login can no longer see the child.",
    ],
    practices: [
      "Promote instead of re-admitting existing students.",
      "Keep parent mobile and email accurate for logins and notices.",
    ],
    related: "Admissions, Parents, Classes, Sections, Attendance, Fees, Exams, Results.",
  }),
  {
    id: "parents",
    title: "Parent Management / Parent Portal",
    moduleId: "student-info",
    keywords: ["parent", "guardian", "portal", "linked students", "read-only"],
    highlightRoles: ["parent"],
    blocks: [
      { type: "h", text: "Purpose" },
      { type: "p", text: "Parents see only their linked children. They cannot create or edit school records." },
      { type: "h", text: "How a parent login is created" },
      { type: "p", text: "Admin opens Student Info → Parents, creates the parent (name, email, phone, relation) and links students. Saving can create a portal username. Admission conversion can also create/link the parent." },
      { type: "h", text: "What a parent can do" },
      { type: "ul", items: [
        "Student Info — view linked children and profiles.",
        "Attendance — view.",
        "Homework — view the homework card (title, class, section, subject, due date, description). No create, edit or delete.",
        "Exams — view schedules for the child’s class.",
        "Marks and Results — view exam-wise marks and the printable report card.",
        "Fees and Payments — view the child’s bills and receipts.",
        "Timetable and Notices — view.",
        "Help — create a support request.",
      ] },
      { type: "h", text: "Active child" },
      { type: "p", text: "If two or more children are linked, the sidebar shows Active child. Switch the child to refresh lists that are child-scoped." },
      { type: "important", text: "Parents never receive Object IDs on screen. They work with names, admission numbers, class and section." },
      { type: "h", text: "Related modules" },
      { type: "p", text: "Student Info, Homework, Exams, Marks, Results, Fees, Notices." },
    ],
  },
  moduleDoc({
    id: "staff-teachers",
    title: "Staff & Teacher Management",
    moduleId: "hr-staff",
    keywords: ["staff", "teacher", "assignment", "employee", "login"],
    highlightRoles: ["admin", "teacher", "hr"],
    purpose: "Create employees, turn teaching staff into Teacher records with portal login, and restrict each teacher to assigned class, section and subject.",
    does: "Settings → Staff stores staff. When staff type is Teacher and portal login is enabled, a Teacher profile and login are synced. Settings → Teacher Assignment maps class/section/subject.",
    who: "Admin and HR with staff / teachers permissions. Teachers can view their own teacher record.",
    features: [
      "Staff create/edit, staff type, portal login.",
      "Teacher list under Teacher → Teachers.",
      "Teacher Assignment: class, section, subject, class-teacher flag.",
      "Teacher context dialog (today’s class) used by homework and similar screens.",
      "Teacher Leave and Salary Slips (see Leave and Payroll chapters).",
    ],
    open: "Settings → Staff. Teachers: Teacher → Teachers. Assignments: Settings → Teacher Assignment.",
    workflow: [
      "Settings → Staff → Create. Enter name and employee details. Set type to Teacher if they teach.",
      "Enable portal login so the teacher can sign in.",
      "Open Settings → Teacher Assignment. Assign Junior KG / Section A / Mathematics (example).",
      "Teacher signs in, picks today’s class if asked, then marks attendance or homework only for that assignment.",
    ],
    create: "Create staff from Settings → Staff, not by inventing a teacher-only form elsewhere. Teacher records are produced from staff sync.",
    edit: "Edit staff on Settings → Staff. Change assignments on Teacher Assignment. Do not leave a teacher assigned to a class they no longer teach.",
    view: "Teacher module lists teachers. Click a name for the profile (designation and details).",
    search: "Search staff/teachers by name, employee ID or email.",
    exportPrint: "List Excel export when the module manager offers it. ID cards can be printed from profile where available.",
    roles: [
      ["Create staff / teacher login", "Yes", "No", "No"],
      ["Assign class/section/subject", "Yes", "No", "No"],
      ["Work in assigned class", "Yes", "Yes", "No"],
    ],
    example: "Priya Sharma is created as Teacher staff with login. She is assigned Junior KG, Section A, Mathematics. She can mark that class only. She cannot open another section’s attendance.",
    mistakes: [
      "Creating a user in Settings → Users without a linked teacher, then expecting class restrictions to apply.",
      "Forgetting Teacher Assignment, so the teacher sees an empty or blocked academic screen.",
    ],
    practices: [
      "One staff record per person.",
      "Review assignments at the start of each session.",
    ],
    related: "Teacher Leave, Payroll, Attendance, Homework, Exams, Marks.",
  }),
  moduleDoc({
    id: "classes-sections",
    title: "Class & Section Management",
    moduleId: "student-info",
    keywords: ["class", "section", "capacity", "class order"],
    purpose: "Define the school structure every other module uses: who sits where, and how many seats a section has.",
    does: "Classes hold the class name and order. Sections belong to a class, have a section name and a capacity. Enrolment and admissions refuse a section that is full.",
    who: "Admin and users with classes.view / sections.view. Teachers and parents view names on records; they do not usually create classes.",
    features: ["Class name and class order.", "Section: class, section name, capacity.", "Used by students, attendance, homework, exams, fees and timetable."],
    open: "Student Info → Classes (/modules/student-info/classes) and Student Info → Sections.",
    workflow: [
      "Create Class (for example Junior KG) and set Class Order so lists sort correctly.",
      "Create Section: choose the Class, Section Name (A), Capacity (for example 30).",
      "Admit or assign students only into sections with a free seat.",
    ],
    create: "Open Classes → Create. Then Sections → Create. Select the class by name, not by an ID.",
    edit: "Edit name, order or capacity. Reducing capacity below current enrolment is blocked or should be avoided.",
    view: "The class and section names appear on student lists, fees and exam screens.",
    search: "Search the class/section lists by name.",
    exportPrint: "Excel export on the list if shown. No separate class certificate.",
    roles: [
      ["Create class/section", "Yes", "No", "No"],
      ["See class name on records", "Yes", "Yes", "Yes"],
    ],
    example: "Create Class Senior KG (order 2), Section A capacity 30. Promotion from Junior KG A targets this section.",
    mistakes: ["Creating two classes with the same name.", "Ignoring capacity and then failing to assign a student."],
    practices: ["Set class order to match the academic ladder.", "Review capacity before admission season."],
    related: "Students, Admissions, Subjects, Attendance, Exams.",
  }),
  moduleDoc({
    id: "subjects",
    title: "Subject Management",
    moduleId: "student-info",
    keywords: ["subject", "subject code", "class order"],
    purpose: "List subjects per class so homework, exams, marks and teacher assignment all use the same names.",
    does: "Each subject has a class, class order, subject name and subject code.",
    who: "Admin with subjects permissions. Teachers see subjects they are assigned. Parents see subject names on homework and marks.",
    features: ["Subject name and code.", "Linked to a class.", "Used in exam schedules, marks columns and homework."],
    open: "Student Info → Subjects (/modules/student-info/subjects).",
    workflow: [
      "Create the class first.",
      "Create subjects for that class (Mathematics, English, …) with a short code.",
      "Assign teachers to those subjects.",
      "When you create an exam, add those subjects to the schedule.",
    ],
    create: "Subjects → Create. Choose Class, enter Subject Name and Subject Code, set Class Order if used.",
    edit: "Edit name or code carefully if marks already exist for that subject.",
    view: "Subject names appear on exam schedules and marks entry; IDs are not shown.",
    search: "Search the subjects list by name.",
    exportPrint: "List export if offered.",
    roles: [
      ["Create subjects", "Yes", "No", "No"],
      ["Use subject in homework/marks", "Yes", "Assigned only", "View name only"],
    ],
    example: "Junior KG has subjects ENG, MAT, EVS. Priya is assigned MAT. Exam schedule lists MAT on Monday 10:00.",
    mistakes: ["Creating the same subject twice for one class.", "Entering marks for a subject not on the exam schedule."],
    practices: ["Keep codes short and stable.", "Align subjects with the exam timetable before marks entry."],
    related: "Classes, Teacher Assignment, Exams, Marks, Homework.",
  }),
  moduleDoc({
    id: "attendance",
    title: "Attendance",
    moduleId: "attendance",
    keywords: ["attendance", "mark", "register", "present", "absent"],
    highlightRoles: ["teacher", "admin", "parent"],
    purpose: "Record who was present on a date for a class and section, and let parents see their child’s attendance.",
    does: "Mark screen for a date/class/section, register views, reports, and settings. Teacher attendance is a separate list for staff.",
    who: "Admin with attendance permissions. Teachers with attendance.create/edit for assigned classes. Parents/students view only.",
    features: [
      "Mark attendance by date, class and section.",
      "Register and reports with date/week/month style filters.",
      "Export/print from reports where the print button exists.",
      "Parent sees the linked child’s attendance only.",
    ],
    open: "Sidebar → Attendance. Mark: /modules/attendance/mark. Register and Reports are tabs in the same module.",
    workflow: [
      "Teacher signs in and confirms today’s class/section if asked.",
      "Open Attendance → Mark.",
      "Select class, section and date (teachers often get assigned values).",
      "Mark each student Present/Absent (or the statuses shown on that screen).",
      "Save.",
    ],
    create: "Saving a mark session creates that day’s register. There is no separate “attendance student” record to invent.",
    edit: "Re-open the same date/class/section and save again if your role has attendance.edit.",
    view: "Register and Reports. Parents use Attendance in the sidebar — view only.",
    search: "Filter by date, class, section and session on register/reports.",
    exportPrint: "Attendance reports offer export/print actions on that page.",
    roles: [
      ["Mark attendance", "Yes", "Assigned class/section", "No"],
      ["View reports", "Yes", "Assigned / view", "Child only"],
    ],
    example: "Priya opens Mark, Junior KG A, today, sets two students Absent, saves. Parent of those students sees the absence on Attendance.",
    mistakes: ["Marking the wrong date.", "A teacher with no assignment cannot load a class list."],
    practices: ["Mark attendance once, at the start of the day.", "Correct the same register rather than creating a parallel sheet."],
    related: "Teacher Assignment, Students, Reports.",
  }),
  moduleDoc({
    id: "homework",
    title: "Homework",
    moduleId: "homework",
    keywords: ["homework", "due date", "assignment", "parent view"],
    highlightRoles: ["teacher", "parent"],
    purpose: "Publish homework for a class, section and subject, and let parents read it.",
    does: "Admin can create homework for any class. Teachers create only for assigned (or today’s) class/section/subject. Parents/students open View and read a popup — no edit or delete.",
    who: "homework.view for all relevant roles. homework.create/edit for admin and teachers. Parents have view only.",
    features: ["Create Homework, Edit, View, Delete (if permitted).", "Fields: class, section, subject, title, description, due date.", "Parent view modal."],
    open: "Sidebar → Homework (/modules/homework).",
    workflow: [
      "Teacher: click Create Homework. Class/section/subject are filled from today’s class when ready.",
      "Enter Title, Description and Due Date.",
      "Create.",
      "Parent: Homework → View → read → close. They cannot change it.",
    ],
    create: "Create Homework. Admin must pick Class, Section and Subject. Teacher uses assigned context.",
    edit: "Edit on the row if you have homework.edit. Teachers cannot move homework to an unassigned class.",
    view: "View opens the read-only card (title, class, section, subject, due date, description, teacher name).",
    search: "The homework table lists class, section, subject, due date and title.",
    exportPrint: "No separate homework certificate. Parents can read on screen.",
    roles: [
      ["Create / edit / delete", "Yes", "Create/edit assigned", "No"],
      ["View", "Yes", "Yes", "Yes (linked class)"],
    ],
    example: "Teacher creates “Practice counting 1–20” for Junior KG A Mathematics due Friday. Parent opens Homework, clicks View, reads the description.",
    mistakes: ["Teacher creating homework before today’s class is selected.", "Expecting parents to upload answers — this module is announcement/view only."],
    practices: ["Write a clear title and due date.", "One homework per subject per day keeps the parent list readable."],
    related: "Teacher Assignment, Subjects, Notices.",
  }),
  moduleDoc({
    id: "exams",
    title: "Examination",
    moduleId: "examination",
    keywords: ["exam", "schedule", "draft", "subjects"],
    purpose: "Define an exam for a class, then schedule subjects with dates and times.",
    does: "Create exam (name, class, start/end, status defaulting to Draft). Add schedule rows per subject. Teachers see assigned class exams. Parents/students view the child’s class exams.",
    who: "exams.view for viewers. exams.create/edit for admin and teachers as permitted. Parents cannot create exams.",
    features: ["Exam list and filters.", "Create / edit exam.", "Schedule subjects.", "Draft vs published-style status on the exam record."],
    open: "Sidebar → Exams (/modules/exams).",
    workflow: [
      "Create Exam: Exam Name, Class, Start Date, End Date, Status (often Draft).",
      "Open the exam and Create Schedule / add subjects with date and time.",
      "Save. Teachers of that class can see the timetable.",
      "Parents see the exam for the linked student’s class.",
    ],
    create: "Exams → Create. Choose the class by name. Then add schedule lines for each subject that will be tested.",
    edit: "Use Edit on the exam if you have exams.edit. Changing class after marks exist should be avoided.",
    view: "Open the exam from the list. Parents use the same Exams menu in view-only mode.",
    search: "Filter the exam list by the fields on that screen (name/class/status).",
    exportPrint: "Print is used more on Results. Exam schedules are on-screen.",
    roles: [
      ["Create / edit exam", "Yes", "If permitted / assigned", "No"],
      ["View schedule", "Yes", "Assigned class", "Child’s class"],
    ],
    example: "Create “Mid Term 2026–27” for Junior KG, 10–20 Sep, Draft. Add Mathematics 10 Sep 10:00, English 11 Sep 10:00. Teachers enter marks later against this exam.",
    mistakes: ["Adding a subject that is not taught in that class.", "Parents trying to create an exam."],
    practices: ["Keep status Draft until the timetable is complete.", "One exam record per term/class, not per subject."],
    related: "Subjects, Marks, Results, Settings → Examination.",
  }),
  moduleDoc({
    id: "marks",
    title: "Marks & Results",
    moduleId: "examination",
    keywords: ["marks", "percentage", "rating", "bulk upload", "excel", "grade"],
    highlightRoles: ["admin", "teacher", "parent"],
    purpose: "Enter marks per exam, student and subject. The system totals marks, percentage and rating. Results show the report card.",
    does: "Create marks by choosing Exam → Class → Section → Student, then entering Total and Gained for each exam subject. Optional class-wise subject entry. Bulk Upload via Excel. Recalculation writes the Result (gained marks, percentage, rating, pass/fail).",
    who: "Admin and teachers with marks.create/edit (teachers only assigned class/section/subject; class teachers may enter all subjects). Parents have marks.view and results.view only.",
    features: [
      "Exam-wise student entry with automatic totals.",
      "Bulk Upload: template, validate, preview, import.",
      "Grade criteria in Settings → Examination.",
      "Results module: exam-wise report card and print.",
    ],
    open: "Sidebar → Marks (/modules/marks). Results: /modules/results. Grade setup: Settings → Examination.",
    workflow: [
      "Create the exam and schedule subjects first.",
      "Open Marks → Create Marks (or enter from the panel).",
      "Select Exam, Class, Section, Student.",
      "Enter Total and Gained for each subject. Totals, percentage and rating update automatically.",
      "Save. Open Results to view/print the report card.",
    ],
    create: "Use Create Marks or class-wise subject save. Do not type student IDs — pick the student by name.",
    edit: "Re-open the student/exam and change gained marks. The result recalculates.",
    view: "Parents: Results → choose exam → report card (student information, exam information, marks table, overall summary).",
    search: "Filter marks/results by exam and class on those panels.",
    exportPrint: "Results → print report card (A4, letterhead kept). Bulk Upload downloads an Excel template.",
    roles: [
      ["Enter / bulk upload marks", "Yes", "Assigned (not parents)", "No"],
      ["View report card", "Yes", "Assigned", "Yes"],
    ],
    example: "Mathematics 80/100, Science 75/100, English 90/100, Hindi 85/100, Social Studies 70/100. Total 400/500 = 80%. Rating follows Settings → Examination grade bands.",
    mistakes: ["Gained marks greater than total.", "Uploading Excel with renamed column headers.", "Parents expecting to edit marks."],
    practices: ["Download a fresh template per exam.", "Fix validation errors before import.", "Set grade criteria before publishing results."],
    related: "Exams, Results, Settings → Examination.",
    extra: [
      { type: "h", text: "Bulk Excel upload" },
      { type: "steps", items: [
        "Marks → Bulk Upload.",
        "Select Exam (optional class/section).",
        "Download Template — one row per student; name columns; each subject has Total and Gained.",
        "Fill the file. Do not add extra header rows.",
        "Upload → Validate → read errors and update flags.",
        "Import only valid rows. Results recalculate for those students.",
      ] },
      { type: "h", text: "Rating / grade configuration" },
      { type: "p", text: "Settings → Examination → grade criteria (for example 90–100 = A+, 85–89.99 = A). The rating on the result is computed from percentage using these bands." },
    ],
  }),
  {
    id: "results-certificates",
    title: "Results & Report Cards",
    moduleId: "report-cards",
    keywords: ["result", "report card", "certificate", "print", "pass", "fail"],
    highlightRoles: ["parent"],
    blocks: [
      { type: "h", text: "Purpose" },
      { type: "p", text: "Results show the exam report card after marks are saved. This is the printable “certificate / marksheet” in the current ERP — there is no separate Certificates module." },
      { type: "h", text: "What is on the report card" },
      { type: "ul", items: [
        "Student information — name, class, section, admission no., roll (from enrolment), session.",
        "Exam information — exam name and type.",
        "Marks table — subject, gained, total, percentage, grade.",
        "Overall total, gained, percentage, rating, pass/fail.",
      ] },
      { type: "steps", items: [
        "Enter marks for the exam.",
        "Open Results.",
        "Select the exam (parents see their child’s exams).",
        "Open the report card.",
        "Print / Save as PDF. Letterhead stays visible; screen chrome is hidden.",
      ] },
      { type: "note", text: "Parents cannot create, edit or delete results. Teachers are limited to assigned classes." },
      { type: "h", text: "Related modules" },
      { type: "p", text: "Marks, Exams, Settings → Examination." },
    ],
  },
];
