import { moduleDoc } from "@/lib/guide/format";
import type { GuideChapter } from "@/lib/guide/types";

export const OPS_CHAPTERS: GuideChapter[] = [
  moduleDoc({
    id: "fees",
    title: "Fees",
    moduleId: "online-fees",
    keywords: ["fees", "due", "pending", "class fees", "fee head"],
    highlightRoles: ["accountant", "admin", "parent"],
    purpose: "Raise student fee demands and track Pending, Partially Paid and Paid.",
    does: "Finance → Fees lists fee rows (admission no., student, class, section, fee head, description, amount, paid, status, due date). Create can raise the same amount for many students in a class/section.",
    who: "fees.view for office and parents (parents see their children). fees.create/edit/collect for admin and accountant.",
    features: [
      "Create class fees: Class + Section → tick students → Amount, Description, Due Date, Status.",
      "Statuses: Pending, Partially Paid, Paid.",
      "Fee structures exist as a related list (name, class, amount, monthly/quarterly/annual).",
    ],
    open: "Finance → Fees (/finance/fees).",
    workflow: [
      "Open Fees → Create (class create dialog).",
      "Select Class and Section. Tick students (or select all).",
      "Enter Amount, Description, Due Date and Status.",
      "Save. Each selected student gets a fee row.",
      "When money arrives, record it under Payments (next chapter).",
    ],
    create: "Use Create Student Fees for a class batch, or the standard create form if you are adding a single row.",
    edit: "Edit amount, description, due date or status if you have fees.edit. Prefer Payments to record collections so paid amounts stay consistent.",
    view: "The fees table. Parents see only linked students — no student IDs.",
    search: "Search/filter the list; status is the usual filter.",
    exportPrint: "Excel on the list if offered. Printed receipts come from Payments, not from the fee row itself.",
    roles: [
      ["Create fees", "Yes", "No", "No"],
      ["View fee status", "Yes", "No", "Yes (own child)"],
      ["Collect (accountant)", "Yes / Accountant", "No", "No"],
    ],
    example: "April tuition ₹2,000 for Junior KG A, due 10 April, status Pending. After a cash collection, Payments creates a receipt and the fee can show Partially Paid or Paid.",
    mistakes: ["Marking Paid without a payment record.", "Selecting the wrong section so the wrong children are billed."],
    practices: ["Use a clear Description (April Tuition).", "Raise fees after the academic session and sections are set."],
    related: "Payments, Students, Admissions (admission fee).",
  }),
  moduleDoc({
    id: "payments",
    title: "Payments",
    moduleId: "online-fees",
    keywords: ["payment", "receipt", "cash", "upi"],
    purpose: "Record money received against fees and print a receipt.",
    does: "Stores amount, method (Cash, UPI, Card, Bank Transfer), receipt number, date and remarks. Print uses school letterhead and student name, class-section, admission no.",
    who: "payments.view for office and parents. Create/edit for admin and accountant.",
    features: ["Create payment.", "Print receipt.", "Methods: CASH, UPI, CARD, BANK."],
    open: "Finance → Payments (/finance/payments).",
    workflow: [
      "Open Payments → Create.",
      "Choose the student (by name), amount, method, date, remarks.",
      "Save. Open Print on the row to get the fee receipt.",
    ],
    create: "Create from the Payments module. Receipt number is stored on the payment.",
    edit: "Edit if you have permission. Do not silently change a printed receipt without a remark.",
    view: "Open the payment or print it. Parents see their child’s receipts.",
    search: "Search the payments list by the configured search fields (student/receipt as shown).",
    exportPrint: "Print / Save as PDF on the payment document. This is the official receipt layout.",
    roles: [
      ["Create payment", "Yes / Accountant", "No", "No"],
      ["View / print receipt", "Yes", "No", "Yes (own child)"],
    ],
    example: "Collect ₹2,000 UPI for April tuition. Print the receipt and hand it to the parent.",
    mistakes: ["Typing a student ID. Always pick the student by name.", "Printing before save."],
    practices: ["Match receipt prefix in Settings → Organization.", "One payment per collection event."],
    related: "Fees, Settings (receipt prefix, logo).",
  }),
  moduleDoc({
    id: "expenses",
    title: "Expenses",
    moduleId: "accounts",
    keywords: ["expense", "voucher", "accounts"],
    highlightRoles: ["accountant", "admin"],
    purpose: "Record school expenses (not student fees).",
    does: "Finance → Expenses is a standard list: create, edit, search and print voucher when offered.",
    who: "expenses.view/create/edit for admin and accountant. Parents do not use this module.",
    features: ["Expense list and create form.", "Print voucher from the document print screen if enabled."],
    open: "Finance → Expenses (/finance/expenses).",
    workflow: ["Open Expenses → Create.", "Enter the expense fields shown (amount, date, notes as on the form).", "Save. Print if you need a voucher."],
    create: "Use Create on the Expenses list.",
    edit: "Edit the row if you have expenses.edit.",
    view: "Open or print the expense.",
    search: "Use the list search box.",
    exportPrint: "Print expense voucher from the print action on the row.",
    roles: [
      ["Create / edit expenses", "Yes / Accountant", "No", "No"],
      ["View", "Yes / Accountant", "No", "No"],
    ],
    example: "Record a stationery purchase with date and amount, then print the voucher for the file.",
    mistakes: ["Booking a student fee collection as an expense."],
    practices: ["Use a clear note so reports stay readable."],
    related: "Reports, Settings (currency).",
  }),
  moduleDoc({
    id: "payroll",
    title: "Payroll & Salary Slips",
    moduleId: "payroll",
    keywords: ["payroll", "salary", "draft", "paid", "slip"],
    highlightRoles: ["hr", "teacher", "admin"],
    purpose: "Prepare monthly salary for staff/teachers and show the slip to the teacher only after it is Paid.",
    does: "Admin/HR create payroll: staff name, employee code, month, basic, allowances, deductions, net pay. Default status is Draft. Teachers do not see Draft. When status is Paid, Teacher → Salary Slips shows the slip.",
    who: "payroll.create/edit for office (Finance → Payroll). Teachers have payroll.view only on their own Paid slips.",
    features: [
      "Finance → Payroll create/edit (Draft / Paid).",
      "Automatic link to teacher by employee code or name.",
      "Teacher → Salary Slips — Paid only.",
      "Print salary slip (letterhead, no internal IDs).",
    ],
    open: "Office: Finance → Payroll. Teacher: Teacher → Salary Slips.",
    workflow: [
      "Finance → Payroll → Create.",
      "Enter Staff Name, Employee ID, Month, Basic, Allowances, Deductions, Net Pay.",
      "Leave Status as Draft while checking figures.",
      "When the salary is released, set Status to Paid and save.",
      "Teacher opens Teacher → Salary Slips → View / Print.",
    ],
    create: "Create from Finance → Payroll. Status defaults to Draft if you leave it empty.",
    edit: "Edit to correct figures or change Draft → Paid. Teachers cannot edit payroll.",
    view: "Office sees all months. Teachers see only their Paid slips.",
    search: "Search by staff name, employee ID or month.",
    exportPrint: "Print salary slip from the print action. Draft slips are not offered to teachers.",
    roles: [
      ["Create / mark Paid", "Yes / HR", "No", "No"],
      ["View Paid slip", "Yes", "Own slip only", "No"],
    ],
    example: "Create June payroll for Priya Sharma as Draft. After transfer, set Paid. Priya then sees June under Salary Slips.",
    mistakes: ["Expecting the teacher to see a Draft slip.", "Mismatching staff name so the slip does not link to the teacher."],
    practices: ["Use the same employee code as on the teacher/staff record.", "Keep Draft until payment is done."],
    related: "Staff, Teacher, Leave.",
  }),
  moduleDoc({
    id: "leave",
    title: "Leave",
    moduleId: "hr-staff",
    keywords: ["leave", "cl", "sl", "holiday", "approve"],
    highlightRoles: ["teacher", "hr", "admin"],
    purpose: "Teachers apply leave. Admin/HR define leave types (CL, SL and yearly days), public holidays, and approve or reject requests.",
    does: "Leave types have name, code and days per year. Public holidays are skipped when counting leave days. Teachers see their balance and cannot create types.",
    who: "leave.view for teachers and office. leave.create for apply (teachers) and types/holidays (office). leave.edit to approve.",
    features: ["Admin tabs: Requests, Leave Types, Public Holidays.", "Teacher: Apply Leave, balance, holidays, own requests.", "Default types Casual Leave (CL, 12) and Sick Leave (SL, 10) if none exist."],
    open: "Sidebar → Leave, or Teacher → Leave.",
    workflow: [
      "Admin: Leave → Leave Types → add CL/SL days if needed. Add Public Holidays.",
      "Teacher: Teacher → Leave → choose type, from/to dates, reason → Submit Request (Pending).",
      "Admin: Leave → Requests → Approve or Reject.",
    ],
    create: "Teachers use Apply Leave. Admin adds types and holidays. Teachers cannot add types.",
    edit: "Admin reviews status. Teachers cannot approve their own leave.",
    view: "Teachers see own requests and remaining days. Admin sees all requests.",
    search: "Use the requests table (teacher name, type, dates, status).",
    exportPrint: "No leave certificate print in this module.",
    roles: [
      ["Apply leave", "Yes", "Yes", "No"],
      ["Create types / holidays / approve", "Yes / HR", "No", "No"],
    ],
    example: "Teacher applies 2 days CL. Holidays in that range are not counted. Admin approves. Balance reduces.",
    mistakes: ["Selecting only public holidays — the system rejects a zero-day range.", "Applying more days than remaining."],
    practices: ["Publish holidays before the term.", "Approve promptly so balances stay correct."],
    related: "Staff, Payroll.",
  }),
  moduleDoc({
    id: "notices",
    title: "Notice Management",
    moduleId: "comms-center",
    keywords: ["notice", "announcement", "audience"],
    purpose: "Publish a school notice to All, Staff, Students or Parents.",
    does: "Create title, body, audience and date. Users see notices for their audience. Click the title to open the full message popup.",
    who: "notices.view for readers. Create/edit/delete for roles that have those permissions (typically Admin). Parents do not create notices unless permitted.",
    features: ["Notice list.", "Audience filter: ALL, STAFF, STUDENTS, PARENTS.", "Unread badge on the header bell.", "Title → detail popup."],
    open: "Header Notices icon, or /modules/notices.",
    workflow: [
      "Admin: Create Notice.",
      "Enter Title, Message (body), Audience, Date.",
      "Save.",
      "Teacher/Parent/Student: open Notices, click the title, read, close.",
    ],
    create: "Create on the Notices module if you have notices.create.",
    edit: "Edit or delete only with notices.edit / notices.delete.",
    view: "Click the notice title. The detail API loads the full message.",
    search: "Search title/body on the list.",
    exportPrint: "Notices are on-screen. No separate notice certificate.",
    roles: [
      ["Create / edit", "Yes", "Only if permitted", "No"],
      ["View own audience", "Yes", "Yes", "Yes"],
    ],
    example: "Admin publishes “PTM on Saturday” to PARENTS. Parents see it in Notices and open the popup.",
    mistakes: ["Choosing Audience = STAFF when you meant parents.", "Putting the whole message only in the title."],
    practices: ["Use a short title and a complete body.", "Set the date so lists sort usefully."],
    related: "Dashboard header, Help.",
  }),
  {
    id: "reports",
    title: "Reports",
    keywords: ["reports", "audit", "summary", "print"],
    blocks: [
      { type: "h", text: "Purpose" },
      { type: "p", text: "Header → Reports opens a workspace summary: counts for key records and a workspace audit log (who did what, when)." },
      { type: "h", text: "How to generate and print" },
      { type: "p", text: "Open Reports. The page loads summary and audit automatically. Click Print / Export to print or save PDF. The school letterhead is included." },
      { type: "h", text: "Other reports" },
      { type: "ul", items: [
        "Admissions → Reports — enquiry/application conversion.",
        "Attendance → Reports — attendance filters and export.",
        "Module Excel export buttons on list pages (where shown).",
      ] },
      { type: "note", text: "You need reports.view (and reports.export where used). Parents typically do not have this header icon." },
      { type: "h", text: "Related modules" },
      { type: "p", text: "Admissions, Attendance, Settings (letterhead)." },
    ],
  },
  moduleDoc({
    id: "library",
    title: "Library",
    moduleId: "library",
    keywords: ["library", "book", "issue", "return", "isbn"],
    purpose: "Catalogue books and issue them to students.",
    does: "Library Books: title, author, ISBN, copies, available. Book Issues: book, student (admission no. and name), issue date, due date, return date, status ISSUED or RETURNED.",
    who: "library.view plus create/issue/return for librarian or admin.",
    features: ["Book catalogue.", "Issue and return via Book Issues.", "Search by title, author, ISBN."],
    open: "Sidebar → Library and Book Issues.",
    workflow: [
      "Add the book (title, copies).",
      "Book Issues → Create. Choose the book and student, set Issue Date and Due Date, status ISSUED.",
      "When the book comes back, set Return Date and status RETURNED. Available copies should stay consistent with copies.",
    ],
    create: "Create books on Library. Create issues on Book Issues.",
    edit: "Edit copies/available carefully. Change issue status to RETURNED on return.",
    view: "Lists show book title and student name — not raw IDs in normal viewing.",
    search: "Search books by title/author/ISBN; issues by status.",
    exportPrint: "Excel on the list if offered. There is no live GPS or overdue-automation screen beyond the due date field.",
    roles: [
      ["Catalogue / issue / return", "Yes / Librarian", "No", "No"],
      ["View", "Yes / Librarian", "No", "No"],
    ],
    example: "Add “Honeydew” with 10 copies. Issue one copy to a student due in 7 days. On return, mark RETURNED.",
    mistakes: ["Issuing when available is 0.", "Leaving status ISSUED after the book is back."],
    practices: ["Keep ISBN unique per title where possible.", "Check due dates weekly."],
    related: "Students.",
  }),
  moduleDoc({
    id: "transport",
    title: "Transport",
    moduleId: "transport",
    keywords: ["transport", "route", "vehicle", "driver", "pickup"],
    purpose: "Record vehicles, routes and which student uses which route.",
    does: "Vehicles (number, type, capacity, driver). Routes (name, stops). Transport Assignments (student, route, pickup point). There is no live GPS tracking screen in this ERP.",
    who: "transport.view/create/edit/assign for transport manager or admin.",
    features: ["Vehicle register.", "Route and stops.", "Student assignment and pickup point."],
    open: "Sidebar → Transport. Assignments are part of the same module resources.",
    workflow: [
      "Add Vehicle (vehicle number, driver, capacity).",
      "Add Route (name and stops).",
      "Assign a student to a route and enter Pickup Point.",
    ],
    create: "Create vehicles, routes, then assignments. Pick students by the fields on the form.",
    edit: "Update driver, stops or pickup as routes change.",
    view: "Lists show vehicle number, route name and student name.",
    search: "Search vehicle number/driver; route name; assignment pickup.",
    exportPrint: "List export if offered. No live map.",
    roles: [
      ["Manage transport", "Yes / Transport Manager", "No", "No"],
      ["View", "Yes", "No", "No"],
    ],
    example: "Vehicle UP14-1234, Route North Line, student assigned pickup “City Park Gate”.",
    mistakes: ["Documenting GPS tracking — it is not implemented.", "Assigning a student without a route."],
    practices: ["Keep vehicle numbers unique.", "Update assignments when a child changes address."],
    related: "Students.",
  }),
  moduleDoc({
    id: "inventory",
    title: "Inventory",
    moduleId: "inventory",
    keywords: ["inventory", "stock", "sku"],
    purpose: "Track stock items and IN/OUT transactions.",
    does: "Items: name, SKU, quantity, unit, location. Transactions: item, type IN or OUT, quantity, date, notes.",
    who: "inventory permissions for admin or an inventory role.",
    features: ["Item master.", "IN/OUT transactions."],
    open: "Sidebar → Inventory.",
    workflow: ["Create the item with SKU and opening quantity.", "Record IN when stock arrives, OUT when it is issued.", "Keep location filled for audits."],
    create: "Create item, then create transactions.",
    edit: "Edit quantity only with care; prefer transactions so history remains.",
    view: "Item and transaction lists.",
    search: "Search name/SKU; transactions by type or notes.",
    exportPrint: "List export if offered.",
    roles: [
      ["Manage stock", "Yes", "No", "No"],
      ["View", "Yes", "No", "No"],
    ],
    example: "Item “A4 Ream”, SKU PAP-A4, IN 20 on 1 June, OUT 2 to office.",
    mistakes: ["Changing quantity without an OUT transaction."],
    practices: ["One SKU per item.", "Date every transaction."],
    related: "Expenses (for purchases) if you also book the bill there.",
  }),
  moduleDoc({
    id: "timetable",
    title: "Timetable",
    moduleId: "timetable",
    keywords: ["timetable", "period", "schedule"],
    purpose: "Store class period plans that teachers, parents and students can view.",
    does: "Standard timetable records for the workspace. Teachers and parents/students have timetable.view.",
    who: "Admin typically creates. Teachers, parents and students view.",
    features: ["Create/edit timetable rows from the Timetable module.", "View in Teacher and parent/student menus."],
    open: "Sidebar → Timetable, or Teacher → Timetable.",
    workflow: ["Admin opens Timetable → Create using the fields on the form.", "Teachers/parents open Timetable to view."],
    create: "Create on the Timetable module if you have timetable.create.",
    edit: "Edit with timetable.edit.",
    view: "Open the timetable list/view for the class.",
    search: "Use the list search.",
    exportPrint: "On-screen view; print via browser if needed.",
    roles: [
      ["Create / edit", "Yes", "Usually no", "No"],
      ["View", "Yes", "Yes", "Yes"],
    ],
    example: "Admin publishes Junior KG A periods. Teacher and parent open Timetable to see them.",
    mistakes: ["Expecting automatic clash detection if you have not set it up — use careful manual entry."],
    practices: ["Align timetable subjects with Teacher Assignment."],
    related: "Classes, Subjects, Teachers.",
  }),
];
