import type { GuideChapter } from "@/lib/guide/types";

export const CLOSING_CHAPTERS: GuideChapter[] = [
  {
    id: "settings",
    title: "Settings",
    keywords: ["settings", "organization", "theme", "letterhead", "email", "users", "roles"],
    highlightRoles: ["admin"],
    blocks: [
      { type: "h", text: "Purpose" },
      { type: "p", text: "Settings configure the school workspace. Open the header gear (desktop) or Settings in the sidebar." },
      { type: "h", text: "Organization" },
      { type: "p", text: "School name, logo upload/remove, address, phone, email, website, currency and receipt prefix. The logo appears on the header and on printed receipts, report cards and salary slips." },
      { type: "h", text: "Users" },
      { type: "p", text: "Settings → Users creates office logins and assigns roles. Do not use this as the only way to create teachers — use Settings → Staff so the teacher profile and class rules stay linked." },
      { type: "h", text: "Staff" },
      { type: "p", text: "Create employees. Teacher staff with portal login become Teacher records." },
      { type: "h", text: "Teacher Assignment" },
      { type: "p", text: "Map teacher → class → section → subject." },
      { type: "h", text: "Roles" },
      { type: "p", text: "View system roles and create custom roles. You can only assign permissions you yourself have." },
      { type: "h", text: "Admission / Student Info / Examination" },
      { type: "p", text: "Admission workflow and fee heads. Student Info session options. Examination grade criteria (A+, A, B+, …)." },
      { type: "h", text: "Theme & letterhead" },
      { type: "p", text: "Settings → Theme chooses the visual theme. Letterhead (school name, logo, address) is used by print documents. Users can also set personal Design under Profile → Design." },
      { type: "h", text: "Email" },
      { type: "p", text: "Settings → Organization includes Email Client configuration for school-side mail (test send is available there). Platform-level email is only for GirjaSoft platform administrators, not school staff." },
      { type: "important", text: "Parents and teachers should not be given Settings access unless they truly administer the school." },
    ],
  },
  {
    id: "roles-permissions",
    title: "User & Role Management",
    keywords: ["roles", "permissions", "rbac", "admin", "teacher", "parent"],
    blocks: [
      { type: "p", text: "Permissions are module + action, for example students.view or fees.collect. Workspace Admin has all permissions. Other system roles are listed below as they ship in the product." },
      { type: "table", headers: ["Area", "Admin", "Teacher", "Parent", "Student", "Accountant"], rows: [
        ["Dashboard / profile", "Yes", "Yes", "Yes", "Yes", "Yes"],
        ["Admissions", "Full", "No*", "No", "No", "No"],
        ["Students / classes", "Full", "View assigned", "Linked child", "Self", "No"],
        ["Attendance", "Full", "Mark assigned", "View child", "View self", "No"],
        ["Homework / exams / marks", "Full", "Create/edit assigned", "View", "View (no marks enter)", "No"],
        ["Results", "Full", "View assigned", "View", "View", "No"],
        ["Fees / payments", "Full", "No", "View child", "No", "Create/collect"],
        ["Expenses / reports", "Full", "No", "No", "No", "Yes"],
        ["Leave apply", "Yes", "Yes", "No", "No", "No"],
        ["Payroll create / Paid", "Yes / HR", "No", "No", "No", "No"],
        ["Salary slip (Paid)", "Yes", "Own only", "No", "No", "No"],
        ["Notices", "Full", "View", "View", "View", "No*"],
        ["Settings", "Full", "No", "No", "No", "No"],
        ["Help tickets", "Yes", "Yes", "Yes", "Yes", "Yes"],
      ] },
      { type: "note", text: "No* means not on the default role. A custom role can add a permission. Always check Settings → Roles for your school." },
      { type: "h", text: "How to create a user" },
      { type: "steps", items: [
        "Settings → Users → Create, or Settings → Staff for employees/teachers.",
        "Assign a role.",
        "Share the username/email and ask the user to change password after first login.",
      ] },
    ],
  },
  {
    id: "support",
    title: "Support Request / Tickets",
    keywords: ["help", "ticket", "support", "incident"],
    blocks: [
      { type: "p", text: "Profile → Help opens Help & Support. You see Open, In Progress, Resolved and Closed counts and your tickets." },
      { type: "steps", items: [
        "Click Create Support Request (to the right of Guide).",
        "Choose type (for example Incident), subject, description, priority, module and page.",
        "Attach a file if needed.",
        "Submit. Open the Ticket ID to add messages.",
      ] },
      { type: "p", text: "GirjaSoft platform staff handle tickets in the platform Tickets module. School users do not need that screen." },
      { type: "important", text: "Guide does not replace tickets. Use Guide to learn the product; use a ticket when something is broken or you need GirjaSoft to act." },
    ],
  },
  {
    id: "guide-chapter",
    title: "How to use this Guide",
    keywords: ["guide", "sop", "manual", "search"],
    blocks: [
      { type: "p", text: "This Guide is the in-app user manual and SOP. Open it from Help → Guide or go to /guide." },
      { type: "ul", items: [
        "Use Contents to jump to a chapter.",
        "Use Search the Guide for phrases such as “upload marks” or “apply leave”.",
        "Use Previous / Next at the bottom.",
        "On a phone, tap Contents to open the chapter list.",
        "Chapters for modules that are disabled in your school are hidden.",
      ] },
    ],
  },
  {
    id: "security",
    title: "Security & Permissions",
    keywords: ["security", "password", "workspace", "permissions"],
    blocks: [
      { type: "ul", items: [
        "Each school workspace is isolated.",
        "Teachers are limited to assigned class/section/subject on write operations.",
        "Parents and students cannot mutate homework, exams, marks or results.",
        "Draft payroll is hidden from teachers.",
        "Change passwords regularly. Use Sign Out on shared computers.",
        "Do not paste internal IDs into documents; the UI uses names and admission numbers.",
      ] },
    ],
  },
  {
    id: "workflows",
    title: "Common Workflows",
    keywords: ["workflow", "sop", "admission", "attendance", "marks", "promotion"],
    blocks: [
      { type: "h", text: "A. New student admission" },
      { type: "steps", items: ["Enquiry (optional)", "Follow-up", "Application or Direct Admission", "Documents and admission fee", "Approve / confirm", "Student + parent created/linked", "Parent login (from parent record)"] },
      { type: "h", text: "B. Daily attendance" },
      { type: "steps", items: ["Teacher login", "Select today’s class/section if asked", "Attendance → Mark", "Set present/absent", "Save"] },
      { type: "h", text: "C. Homework" },
      { type: "steps", items: ["Teacher → Homework → Create", "Title, description, due date", "Create", "Parent → Homework → View"] },
      { type: "h", text: "D. Examination to result" },
      { type: "steps", items: ["Create Exam + schedule subjects", "Conduct the exam", "Marks → enter or Bulk Upload", "Open Results", "Parent views / prints report card"] },
      { type: "h", text: "E. Bulk marks" },
      { type: "steps", items: ["Marks → Bulk Upload", "Select exam", "Download template", "Fill one row per student", "Validate", "Fix errors", "Import"] },
      { type: "h", text: "F. Student promotion" },
      { type: "steps", items: ["Student Info → Promotion", "Choose session and from/to class-section", "Select students", "Promote", "Same student record continues in the new class"] },
      { type: "h", text: "G. Teacher salary" },
      { type: "steps", items: ["Finance → Payroll → Create (Draft)", "Check figures", "Set Paid", "Teacher → Salary Slips → Print"] },
    ],
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    keywords: ["problem", "error", "cannot see", "excel", "forbidden"],
    blocks: [
      { type: "h", text: "Teacher cannot see a class" },
      { type: "p", text: "The teacher is not assigned to that class/section/subject. Admin: Settings → Teacher Assignment." },
      { type: "h", text: "Teacher cannot create homework" },
      { type: "p", text: "Today’s class is not selected, or the teacher has no assignment. Use the class banner Change action." },
      { type: "h", text: "Parent cannot see marks or results" },
      { type: "p", text: "Marks may not be entered yet, the child is not linked on the parent record, or the wrong Active child is selected." },
      { type: "h", text: "Excel upload fails" },
      { type: "ul", items: ["Column headers were changed.", "Student name/class/section do not match.", "Gained marks exceed total.", "Exam or subject missing.", "Fix the preview errors, then import only valid rows."] },
      { type: "h", text: "Teacher cannot see a salary slip" },
      { type: "p", text: "Payroll is still Draft, or staff name/employee code does not match the teacher." },
      { type: "h", text: "Leave request rejected as zero days" },
      { type: "p", text: "The chosen dates fall only on public holidays. Pick working days." },
      { type: "h", text: "Section has no seat" },
      { type: "p", text: "Capacity is full. Increase capacity or choose another section." },
      { type: "h", text: "Module missing from the sidebar" },
      { type: "p", text: "The module is disabled for the workspace, or your role lacks the view permission." },
    ],
  },
  {
    id: "faq",
    title: "FAQ",
    keywords: ["faq", "how do i", "question"],
    blocks: [
      { type: "h", text: "How do I create a student?" },
      { type: "p", text: "Prefer Admissions conversion, or Student Info → Students → Create (admission number and name). Assign class/section if a seat exists." },
      { type: "h", text: "How do I create a teacher?" },
      { type: "p", text: "Settings → Staff, type Teacher, enable portal login. Then Settings → Teacher Assignment." },
      { type: "h", text: "How do I mark attendance?" },
      { type: "p", text: "Attendance → Mark → class, section, date → save." },
      { type: "h", text: "How do I create homework?" },
      { type: "p", text: "Homework → Create Homework → title, due date, class/section/subject → Create." },
      { type: "h", text: "How do I create an exam?" },
      { type: "p", text: "Exams → Create → name, class, dates → add subject schedule." },
      { type: "h", text: "How do I enter or upload marks?" },
      { type: "p", text: "Marks: exam → student → totals/gained. Or Bulk Upload → template → validate → import." },
      { type: "h", text: "How is percentage and rating calculated?" },
      { type: "p", text: "Percentage is gained ÷ total × 100 for the exam. Rating uses Settings → Examination grade bands." },
      { type: "h", text: "How does a parent view marks?" },
      { type: "p", text: "Parent login → Results (or Marks) → select exam → report card." },
      { type: "h", text: "How do I promote students?" },
      { type: "p", text: "Student Info → Promotion. Do not create a new student for the next class." },
      { type: "h", text: "How do I create a notice?" },
      { type: "p", text: "Notices → Create → title, body, audience, date." },
      { type: "h", text: "How do I raise a support request?" },
      { type: "p", text: "Profile → Help → Create Support Request." },
      { type: "h", text: "Where is the Guide?" },
      { type: "p", text: "Profile → Help → Guide, or open /guide." },
    ],
  },
  {
    id: "best-practices",
    title: "Best Practices",
    keywords: ["best practice", "sop", "quality"],
    blocks: [
      { type: "ul", items: [
        "Set organisation, logo, sessions, classes, sections and subjects before admissions.",
        "One person, one staff/teacher/student record.",
        "Promote students; never clone them for a new year.",
        "Assign teachers before the first attendance day.",
        "Keep payroll Draft until money is paid.",
        "Use names and admission numbers, never internal IDs, in conversation and print.",
        "Train new staff on this Guide in their first week.",
        "Raise a Help ticket only after you have checked Troubleshooting.",
      ] },
    ],
  },
];
