"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { DocumentLetterhead, type Letterhead } from "@/components/DocumentLetterhead";
import { PaymentReceipt } from "@/components/payments/PaymentReceipt";
import { SalarySlip } from "@/components/payroll/SalarySlip";
import { ResultReportCard, type ResultReport } from "@/components/results/ResultReportCard";
import { PRINTABLE_DOCUMENTS, isPrintableDocument } from "@/config/documents";
import { api } from "@/lib/client";

const HIDDEN_PRINT_KEYS = new Set([
  "_id",
  "id",
  "workspaceId",
  "__v",
  "createdAt",
  "updatedAt",
  "examId",
  "studentId",
  "subjectId",
  "classId",
  "sectionId",
]);

export default function PrintDocumentPage() {
  const params = useParams<{ type: string; id: string }>();
  const type = params.type;
  const id = params.id;
  const [letterhead, setLetterhead] = useState<Letterhead | null>(null);
  const [item, setItem] = useState<Record<string, unknown> | null>(null);
  const [report, setReport] = useState<ResultReport | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!isPrintableDocument(type)) {
      setError("This document type cannot be printed.");
      return;
    }
    const load = async () => {
      const brand = await api<{ letterhead: Letterhead }>("/api/workspace/letterhead");
      setLetterhead(brand.letterhead);
      if (type === "results") {
        const data = await api<{ item: ResultReport }>(`/api/results/${id}/report`);
        setReport(data.item);
        return;
      }
      if (type === "payroll") {
        try {
          const slip = await api<{ item: Record<string, unknown> }>(`/api/payroll/slips/${id}`);
          setItem(slip.item);
          return;
        } catch {
          const record = await api<{ item: Record<string, unknown> }>(`/api/payroll/${id}`);
          setItem(record.item);
          return;
        }
      }
      const record = await api<{ item: Record<string, unknown> }>(`/api/${type}/${id}`);
      setItem(record.item);
    };
    load().catch((err) => setError(err instanceof Error ? err.message : "Could not load the document."));
  }, [type, id]);

  const meta = PRINTABLE_DOCUMENTS[type];

  return (
    <div className="mx-auto max-w-3xl p-8 print:p-0">
      <div className="mb-4 flex justify-end print:hidden">
        <button className="gs-btn px-4 py-2" onClick={() => window.print()}>
          Print / Save as PDF
        </button>
      </div>
      {error ? <p className="text-red-600">{error}</p> : null}
      {letterhead && report ? <ResultReportCard item={report} letterhead={letterhead} /> : null}
      {letterhead && item && type === "payments" && !report ? (
        <PaymentReceipt item={item} letterhead={letterhead} />
      ) : null}
      {letterhead && item && type === "payroll" && !report ? (
        <SalarySlip item={item} letterhead={letterhead} />
      ) : null}
      {letterhead && item && type !== "payments" && type !== "payroll" && !report ? (
        <article className="document-sheet border border-slate-200 p-8">
          <DocumentLetterhead letterhead={letterhead} title={meta.title} />
          <dl className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
            {Object.entries(item)
              .filter(([key]) => !HIDDEN_PRINT_KEYS.has(key) && !key.toLowerCase().endsWith("id"))
              .map(([key, value]) => (
                <div key={key}>
                  <dt className="text-slate-500 capitalize">{key.replace(/([A-Z])/g, " $1")}</dt>
                  <dd className="font-medium">{String(value ?? "")}</dd>
                </div>
              ))}
          </dl>
          <p className="mt-10 text-xs text-slate-500">
            Generated by {letterhead.appName}. This is a system-generated document.
          </p>
        </article>
      ) : null}
      {!error && !letterhead ? <p>Preparing document…</p> : null}
    </div>
  );
}
