"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import { DocumentLetterhead, type Letterhead } from "@/components/DocumentLetterhead";
import { PRINTABLE_DOCUMENTS, isPrintableDocument } from "@/config/documents";
import { api } from "@/lib/client";

export default function PrintDocumentPage() {
  const params = useParams<{ type: string; id: string }>();
  const type = params.type;
  const id = params.id;
  const [letterhead, setLetterhead] = useState<Letterhead | null>(null);
  const [item, setItem] = useState<Record<string, unknown> | null>(null);
  const [error, setError] = useState("");

  useEffect(() => {
    if (!isPrintableDocument(type)) {
      setError("This document type cannot be printed.");
      return;
    }
    Promise.all([
      api<{ letterhead: Letterhead }>("/api/workspace/letterhead"),
      api<{ item: Record<string, unknown> }>(`/api/${type}/${id}`),
    ])
      .then(([brand, record]) => {
        setLetterhead(brand.letterhead);
        setItem(record.item);
      })
      .catch((err) => setError(err.message));
  }, [type, id]);

  const meta = PRINTABLE_DOCUMENTS[type];

  return (
    <div className="max-w-3xl mx-auto p-8 print:p-0">
      <div className="mb-4 flex justify-end print:hidden">
        <button className="gs-btn px-4 py-2" onClick={() => window.print()}>
          Print
        </button>
      </div>
      {error ? <p className="text-red-600">{error}</p> : null}
      {letterhead && item ? (
        <article className="document-sheet border border-slate-200 p-8">
          <DocumentLetterhead letterhead={letterhead} title={meta.title} />
          <dl className="grid grid-cols-2 gap-x-6 gap-y-3 text-sm">
            {Object.entries(item)
              .filter(([key]) => !["_id", "workspaceId", "__v", "createdAt", "updatedAt"].includes(key))
              .map(([key, value]) => (
                <div key={key}>
                  <dt className="text-slate-500 capitalize">{key.replace(/([A-Z])/g, " $1")}</dt>
                  <dd className="font-medium">{String(value ?? "")}</dd>
                </div>
              ))}
          </dl>
          <p className="mt-10 text-xs text-slate-500">
            Generated by {letterhead.appName}. This is a system-generated document.
          </p>
        </article>
      ) : !error ? (
        <p>Preparing document…</p>
      ) : null}
    </div>
  );
}
